In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("olist_products_dataset_cle.csv")
df.head(10)

,product_id,Product_Category_Name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumaria,40,287,1,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,Artes,44,276,1,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,Esporte_Lazer,46,250,1,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,Bebes,27,261,1,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,Utilidades_Domesticas,37,402,4,625,20,17,13
5,41d3672d4792049fa1779bb35283ed13,Instrumentos_Musicais,60,745,1,200,38,5,11
6,732bd381ad09e530fe0a5f457d81becb,Cool_Stuff,56,1272,4,18350,70,24,44
7,2548af3e6e77a690cf3eb6368e9ab61e,Moveis_Decoracao,56,184,2,900,40,8,40
8,37cc742be07708b53a98702e77a21a02,Eletrodomesticos,57,163,1,400,27,13,17
9,8c92109888e8cdf9d66dc7e463025574,Brinquedos,36,1156,1,600,17,10,12

In [4]:
df.isnull().sum()

product_id                    0
Product_Category_Name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32340 entries, 0 to 32339
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  object
 1   Product_Category_Name       32340 non-null  object
 2   product_name_length         32340 non-null  int64
 3   product_description_length  32340 non-null  int64
 4   product_photos_qty          32340 non-null  int64
 5   product_weight_g            32340 non-null  int64
 6   product_length_cm           32340 non-null  int64
 7   product_height_cm           32340 non-null  int64
 8   product_width_cm            32340 non-null  int64
dtypes: int64(7), object(2)
memory usage: 2.2+ MB

In [7]:
df.describe()

,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32340.000000,32340.000000,32340.000000,32340.000000,32340.000000,32340.000000,32340.000000
mean,48.476592,771.492393,2.188961,2276.956586,30.854545,16.958813,23.208596
std,10.245699,635.124831,1.736787,4279.291845,16.955965,13.636115,12.078762
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [8]:
df["product_weight_g"].describe()

count    32340.000000
mean      2276.956586
std       4279.291845
min          0.000000
25%        300.000000
50%        700.000000
75%       1900.000000
max      40425.000000
Name: product_weight_g, dtype: float64

In [9]:
df.dtypes

product_id                    object
Product_Category_Name         object
product_name_length            int64
product_description_length     int64
product_photos_qty             int64
product_weight_g               int64
product_length_cm              int64
product_height_cm              int64
product_width_cm               int64
dtype: object

In [10]:
df["Product_Category_Name"].unique()

array(['Perfumaria', 'Artes', 'Esporte_Lazer', 'Bebes',
       'Utilidades_Domesticas', 'Instrumentos_Musicais', 'Cool_Stuff',
       'Moveis_Decoracao', 'Eletrodomesticos', 'Brinquedos',
       'Cama_Mesa_Banho', 'Construcao_Ferramentas_Seguranca',
       'Informatica_Acessorios', 'Beleza_Saude', 'Malas_Acessorios',
       'Ferramentas_Jardim', 'Moveis_Escritorio', 'Automotivo',
       'Eletronicos', 'Fashion_Calcados', 'Telefonia', 'Papelaria',
       'Fashion_Bolsas_E_Acessorios', 'Pcs', 'Casa_Construcao',
       'Relogios_Presentes', 'Construcao_Ferramentas_Construcao',
       'Pet_Shop', 'Eletroportateis', 'Agro_Industria_E_Comercio',
       'Moveis_Sala', 'Sinalizacao_E_Seguranca', 'Climatizacao',
       'Consoles_Games', 'Livros_Interesse_Geral',
       'Construcao_Ferramentas_Ferramentas',
       'Fashion_Underwear_E_Moda_Praia', 'Fashion_Roupa_Masculina',
       'Moveis_Cozinha_Area_De_Servico_Jantar_E_Jardim',
       'Industria_Comercio_E_Negocios', 'Telefonia_Fixa',
       'Construcao_Ferramentas_Iluminacao', 'Livros_Tecnicos',
       'Eletrodomesticos_2', 'Artigos_De_Festas', 'Bebidas',
       'Market_Place', 'La_Cuisine', 'Construcao_Ferramentas_Jardim',
       'Fashion_Roupa_Feminina', 'Casa_Conforto', 'Audio',
       'Alimentos_Bebidas', 'Musica', 'Alimentos',
       'Tablets_Impressao_Imagem', 'Livros_Importados',
       'Portateis_Casa_Forno_E_Cafe', 'Fashion_Esporte',
       'Artigos_De_Natal', 'Fashion_Roupa_Infanto_Juvenil',
       'Dvds_Blu_Ray', 'Artes_E_Artesanato', 'Pc_Gamer', 'Moveis_Quarto',
       'Cine_Foto', 'Fraldas_Higiene', 'Flores', 'Casa_Conforto_2',
       'Portateis_Cozinha_E_Preparadores_De_Alimentos',
       'Seguros_E_Servicos', 'Moveis_Colchao_E_Estofado',
       'Cds_Dvds_Musicais'], dtype=object)

product category name wise average weight,length,heigh and width

In [14]:
df.groupby("product_category_name")[[
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]].mean()

,product_weight_g,product_length_cm,product_height_cm,product_width_cm
product_category_name,,,,
Agro_Industria_E_Comercio,5263.405405,36.527027,28.945946,25.810811
Alimentos,923.414634,21.292683,14.682927,17.719512
Alimentos_Bebidas,1307.932692,23.403846,15.951923,18.394231
Artes,1691.763636,35.927273,11.800000,23.363636
Artes_E_Artesanato,1164.578947,28.368421,9.789474,21.052632
...,...,...,...,...
Sinalizacao_E_Seguranca,2969.817204,30.505376,23.892473,20.817204
Tablets_Impressao_Imagem,381.444444,28.111111,9.444444,21.555556
Telefonia,236.506173,18.432981,6.853616,13.248677
Telefonia_Fixa,660.827586,20.646552,10.741379,16.500000
Utilidades_Domesticas,3020.793576,31.859957,22.337901,24.821413

In [13]:
df.columns = df.columns.str.lower()

product category name wise mean,median,min and max weight,length,heigh and width

In [ ]:
df.groupby("product_category_name")[[
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]].agg(["mean", "median", "min", "max"])

                          product_weight_g                      \
                                      mean  median  min    max
product_category_name
Agro_Industria_E_Comercio      5263.405405  2681.5   50  30000
Alimentos                       923.414634   541.5   75   8238
Alimentos_Bebidas              1307.932692   600.0   50  10800
Artes                          1691.763636   700.0  100  15400
Artes_E_Artesanato             1164.578947   500.0  100   6850
...                                    ...     ...  ...    ...
Sinalizacao_E_Seguranca        2969.817204   575.0  100  27100
Tablets_Impressao_Imagem        381.444444   300.0  100   1100
Telefonia                       236.506173   200.0   50   8100
Telefonia_Fixa                  660.827586   414.5   50   6050
Utilidades_Domesticas          3020.793576  1050.0   50  30000

                          product_length_cm                 product_height_cm  \
                                       mean median min  max              mean
product_category_name
Agro_Industria_E_Comercio         36.527027   31.5  11   99         28.945946
Alimentos                         21.292683   19.5  16   44         14.682927
Alimentos_Bebidas                 23.403846   21.0  16   57         15.951923
Artes                             35.927273   30.0  16  100         11.800000
Artes_E_Artesanato                28.368421   21.0  16  105          9.789474
...                                     ...    ...  ..  ...               ...
Sinalizacao_E_Seguranca           30.505376   25.0  16  100         23.892473
Tablets_Impressao_Imagem          28.111111   26.0  16   60          9.444444
Telefonia                         18.432981   18.0  12   40          6.853616
Telefonia_Fixa                    20.646552   19.0  14  100         10.741379
Utilidades_Domesticas             31.859957   30.0  10  105         22.337901

                                          product_width_cm
                          median min  max             mean median min max
product_category_name
Agro_Industria_E_Comercio   25.5   2  105        25.810811   24.0  10  80
Alimentos                   14.0   4   52        17.719512   16.0  11  36
Alimentos_Bebidas           15.0   2   40        18.394231   17.0  11  30
Artes                       10.0   2   62        23.363636   20.0  11  70
Artes_E_Artesanato           9.0   2   25        21.052632   16.0  11  65
...                          ...  ..  ...              ...    ...  ..  ..
Sinalizacao_E_Seguranca     15.0   2  105        20.817204   20.0  11  53
Tablets_Impressao_Imagem     6.0   3   27        21.555556   21.0  11  40
Telefonia                    5.0   2   51        13.248677   12.0   8  30
Telefonia_Fixa               9.0   2   30        16.500000   16.0   9  33
Utilidades_Domesticas       20.0   2  105        24.821413   24.0  11  90

[73 rows x 16 columns]

In [ ]:
df.groupby("product_category_name")[[
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]].mean().sort_values(
    by="product_weight_g",
    ascending=False
).round(2)

,product_weight_g,product_length_cm,product_height_cm,product_width_cm
product_category_name,,,,
Moveis_Colchao_E_Estofado,13190.00,46.30,34.40,41.30
Moveis_Escritorio,12740.87,55.63,41.86,37.92
Moveis_Cozinha_Area_De_Servico_Jantar_E_Jardim,11598.56,47.34,40.48,38.68
Moveis_Quarto,9997.22,59.93,30.80,34.40
Eletrodomesticos_2,9913.33,45.73,30.67,38.17
...,...,...,...,...
Tablets_Impressao_Imagem,381.44,28.11,9.44,21.56
Fashion_Underwear_E_Moda_Praia,362.26,25.51,8.85,18.91
Fashion_Esporte,344.74,22.11,12.84,16.26
Fashion_Roupa_Infanto_Juvenil,324.00,27.40,13.40,20.60
Telefonia,236.51,18.43,6.85,13.25

In [ ]:
df.groupby("product_category_name")["product_id"].count().sort_values(ascending=False)

product_category_name
Cama_Mesa_Banho                  3029
Esporte_Lazer                    2867
Moveis_Decoracao                 2657
Beleza_Saude                     2444
Utilidades_Domesticas            2335
                                 ...
Casa_Conforto_2                     5
Fashion_Roupa_Infanto_Juvenil       5
Pc_Gamer                            3
Seguros_E_Servicos                  2
Cds_Dvds_Musicais                   1
Name: product_id, Length: 73, dtype: int64

product category wise count of products,avg weight and length

In [ ]:
df.groupby("product_category_name").agg(
    product_count=("product_id", "count"),
    avg_weight=("product_weight_g", "mean"),
    avg_length=("product_length_cm", "mean")
).sort_values(by="product_count", ascending=False)

                               product_count   avg_weight  avg_length
product_category_name
Cama_Mesa_Banho                         3029  2456.405084   36.774183
Esporte_Lazer                           2867  2024.670736   31.280084
Moveis_Decoracao                        2657  3008.266842   43.894994
Beleza_Saude                            2444  1434.793781   23.800736
Utilidades_Domesticas                   2335  3020.793576   31.859957
...                                      ...          ...         ...
Casa_Conforto_2                            5  1467.600000   53.200000
Fashion_Roupa_Infanto_Juvenil              5   324.000000   27.400000
Pc_Gamer                                   3  1429.666667   17.666667
Seguros_E_Servicos                         2   812.500000   26.500000
Cds_Dvds_Musicais                          1   550.000000   35.000000

[73 rows x 3 columns]

In [ ]:
df.groupby("product_category_name").agg(
    maximum_weight = ("product_weight_g","max")
).sort_values (by = "maximum_weight",ascending = False)

                               maximum_weight
product_category_name
Cama_Mesa_Banho                         40425
Agro_Industria_E_Comercio               30000
Consoles_Games                          30000
Cool_Stuff                              30000
Eletrodomesticos                        30000
...                                       ...
Livros_Importados                        1300
Seguros_E_Servicos                       1225
Tablets_Impressao_Imagem                 1100
Fashion_Roupa_Infanto_Juvenil             600
Cds_Dvds_Musicais                         550

[73 rows x 1 columns]

In [ ]:
df.groupby("product_category_name").agg(
    max_weight = ("product_weight_g","max"),
    min_weight = ("product_weight_g","min"),
    mean_weight = ("product_weight_g","mean"),
    product_count = ("product_id","count")
).sort_values(by = "product_count",ascending = False)

,max_weight,min_weight,mean_weight,product_count
product_category_name,,,,
Cama_Mesa_Banho,40425,0,2456.405084,3029
Esporte_Lazer,30000,50,2024.670736,2867
Moveis_Decoracao,30000,2,3008.266842,2657
Beleza_Saude,30000,50,1434.793781,2444
Utilidades_Domesticas,30000,50,3020.793576,2335
...,...,...,...,...
Casa_Conforto_2,3750,425,1467.600000,5
Fashion_Roupa_Infanto_Juvenil,600,100,324.000000,5
Pc_Gamer,2839,650,1429.666667,3
Seguros_E_Servicos,1225,400,812.500000,2
Cds_Dvds_Musicais,550,550,550.000000,1

In [ ]:
df.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [ ]:
df["product_volume_cm3"] = (
    df["product_length_cm"]*
    df["product_height_cm"]*
    df["product_width_cm"]
)

In [ ]:
df.groupby("product_category_name").agg(
    average_volume = ("product_volume_cm3","mean")
).sort_values("average_volume",ascending = False).round(2)

                                                average_volume
product_category_name
Moveis_Colchao_E_Estofado                             77244.30
Moveis_Escritorio                                     75468.47
Moveis_Cozinha_Area_De_Servico_Jantar_E_Jardim        69406.10
Eletrodomesticos_2                                    55476.31
Moveis_Sala                                           54486.13
...                                                        ...
Relogios_Presentes                                     3470.40
Livros_Tecnicos                                        2758.99
Livros_Importados                                      1935.39
Telefonia                                              1865.84
Dvds_Blu_Ray                                           1746.85

[73 rows x 1 columns]

In [ ]:
df["product_volume_cm3"] = (
    df["product_length_cm"] *
    df["product_height_cm"] *
    df["product_width_cm"]
)

df.groupby("product_category_name").agg(
    avg_length=("product_length_cm", "mean"),
    avg_height=("product_height_cm", "mean"),
    avg_width=("product_width_cm", "mean"),
    avg_weight=("product_weight_g", "mean"),
    avg_volume=("product_volume_cm3", "mean")
).sort_values(by="avg_volume", ascending=False).round(2)

,avg_length,avg_height,avg_width,avg_weight,avg_volume
product_category_name,,,,,
Moveis_Colchao_E_Estofado,46.30,34.40,41.30,13190.00,77244.30
Moveis_Escritorio,55.63,41.86,37.92,12740.87,75468.47
Moveis_Cozinha_Area_De_Servico_Jantar_E_Jardim,47.34,40.48,38.68,11598.56,69406.10
Eletrodomesticos_2,45.73,30.67,38.17,9913.33,55476.31
Moveis_Sala,50.73,22.37,44.43,8934.85,54486.13
...,...,...,...,...,...
Relogios_Presentes,19.22,10.29,15.27,509.29,3470.40
Livros_Tecnicos,27.33,5.87,18.46,1107.85,2758.99
Livros_Importados,29.74,3.45,21.23,596.77,1935.39
Telefonia,18.43,6.85,13.25,236.51,1865.84
Dvds_Blu_Ray,21.27,4.42,14.88,381.56,1746.85

In [ ]:
df.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'product_volume_cm3'],
      dtype='object')

In [ ]:
df.groupby("product_category_name").agg(
    max_photos=("product_photos_qty", "max")
).sort_values(by="max_photos", ascending=False)

                             max_photos
product_category_name
Brinquedos                           20
Bebes                                19
Pet_Shop                             18
Moveis_Decoracao                     15
Fashion_Bolsas_E_Acessorios          15
...                                 ...
Seguros_E_Servicos                    4
Flores                                3
Cds_Dvds_Musicais                     2
Casa_Conforto_2                       2
La_Cuisine                            2

[73 rows x 1 columns]

In [ ]:
df[[
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]].describe()

,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32340.000000,32340.000000,32340.000000,32340.000000
mean,2276.956586,30.854545,16.958813,23.208596
std,4279.291845,16.955965,13.636115,12.078762
min,0.000000,7.000000,2.000000,6.000000
25%,300.000000,18.000000,8.000000,15.000000
50%,700.000000,25.000000,13.000000,20.000000
75%,1900.000000,38.000000,21.000000,30.000000
max,40425.000000,105.000000,105.000000,118.000000

In [ ]:
for col in [
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print(col, len(outliers))

product_weight_g 4478
product_length_cm 1365
product_height_cm 1870
product_width_cm 897

In [12]:
565 in df["product_weight_g"].values

False