In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option("display.max_rows", None)

In [3]:
orders = pd.read_csv("olist_orders_cleaned_dataset.csv")
customers = pd.read_csv("olist_customers_dataset_cle.csv")
sellers = pd.read_csv("olist_sellers_dataset_cle.csv",encoding="cp1252")
products = pd.read_csv("olist_products_dataset_cle.csv")
order_items = pd.read_csv("olist_orders_items_cleaned.csv")
reviews = pd.read_csv("olist_order_reviews_dataset_cle.csv")
payments = pd.read_csv("olist_order_payments_dataset_cle.csv")
geolocation = pd.read_csv("olist_geolocation_dataset_cle.csv")

In [5]:
payments.dtypes

order_id                object
payment_sequential       int64
payment_type            object
payment_installments     int64
payment_value           object
dtype: object

In [10]:
payments = payments.rename(columns={"payment_value " : "payment_value"})

0            99.33
1            24.39
2            65.71
3           107.78
4           128.45
5            96.12
6            81.16
7            51.84
8           341.09
9            51.95
10          188.73
11          141.90
12           75.78
13          102.66
14          105.28
15          157.45
16          132.04
17           98.94
18          244.15
19          136.71
20           47.69
21          170.57
22           67.50
23          353.09
24          330.66
25           45.17
26          541.00
27          139.22
28          290.16
29          283.34
30           13.78
31           30.28
32           26.58
33           89.68
34           65.09
35          173.84
36          103.49
37           64.03
38          157.15
39          130.88
40           47.72
41          117.74
42           56.60
43          266.16
44           31.38
45          121.49
46           32.00
47          153.41
48           65.71
49          278.22
50           91.66
51          132.51
52          542.66
53          166.04
54          368.98
55          113.20
56           99.43
57           27.35
58           43.77
59           68.49
60          105.53
61          387.80
62           84.14
63          210.82
64           90.05
65           67.88
66           37.58
67           89.63
68           69.46
69           78.30
70           50.80
71           34.00
72           77.10
73          566.40
74          402.42
75           57.53
76           44.01
77          187.51
78           77.70
79           48.68
80           77.29
81          117.71
82          169.34
83           37.61
84           13.80
85          227.12
86           34.78
87          342.56
88           73.34
89          117.85
90           48.62
91           53.99
92           51.14
93          121.45
94           73.34
95          117.68
96           56.77
97          115.59
98           60.07
99           27.27
100          32.15
101         195.71
102          43.12
103          88.49
104          34.09
105          40.99
106          71.99
107          47.00
108          81.78
109         231.45
110         144.20
111          35.14
112         285.79
113         176.70
114          27.63
115         134.56
116          96.98
117         110.03
118          17.78
119          44.00
120         110.11
121          22.49
122          46.63
123          52.21
124          61.77
125         121.88
126          75.75
127         130.22
128          57.53
129          76.02
130          90.17
131          31.00
132         106.77
133         163.25
134         233.66
135         163.08
136         135.93
137         267.05
138         186.72
139          30.00
140          97.28
141          48.61
142         116.70
143          41.42
144          42.19
145         125.53
146          92.76
147         348.02
148         203.30
149          44.35
150         116.05
151          85.14
152         236.66
153         220.30
154         180.55
155          45.46
156          26.08
157         375.74
158         123.41
159         379.07
160        2027.16
161          45.50
162          91.17
163          93.26
164          30.00
165         165.96
166          50.00
167        1002.73
168         116.56
169         240.52
170          33.13
171         213.90
172         362.17
173          88.72
174          46.85
175          68.54
176          32.62
177         340.08
178          82.06
179          40.95
180          67.01
181          20.00
182          76.90
183          40.27
184         242.10
185         207.24
186         215.56
187          39.92
188         156.09
189         131.50
190         137.73
191          31.75
192         348.77
193          12.22
194         139.87
195         257.10
196         269.46
197          40.00
198         350.09
199         134.55
200         112.73
201          72.05
202           0.67
203          77.77
204          26.68
205         371.42
206         225.71
207         103.79
208          65.00
209          69.80
210          20.09
211         125.41
212          95.99
213          25.33
214          52.57
215         145.58
216          49.70
217          47.43
218         168.57
219         133.81
220           1.23
221         123.82
222         283.66
223          89.88
224          32.38
225          43.08
226         254.58
227          48.91
228          48.22
229          67.58
230         311.18
231         154.14
232         333.68
233         404.88
234          44.77
235        1302.42
236         645.80
237         186.39
238         208.41
239          76.39
240          67.42
241         232.05
242          69.33
243         641.20
244          41.86
245          50.00
246         106.96
247        2288.31
248          69.90
249          88.08
250         117.39
251         194.91
252          68.89
253         151.51
254          54.85
255         103.68
256         225.63
257          39.60
258         159.18
259         234.43
260          44.83
261         205.44
262          13.55
263         221.96
264          52.38
265         131.47
266          38.06
267          35.00
268         143.65
269          86.73
270         118.35
271         341.58
272         105.42
273          68.16
274         357.97
275           2.99
276          92.57
277          68.35
278         197.23
279         153.67
280          46.43
281         102.03
282         119.45
283          44.23
284          67.50
285           8.75
286          44.27
287          37.15
288         114.13
289         396.97
290         185.85
291          62.11
292          25.23
293         153.22
294         145.01
295          70.89
296         114.34
297          31.38
298         256.50
299         341.40
300         143.99
301          84.88
302         232.27
303         194.00
304         260.57
305          49.59
306         196.55
307         245.94
308          72.42
309         217.15
310         152.28
311          72.34
312         128.95
313          56.85
314          20.29
315         171.75
316          85.82
317          56.05
318          26.09
319          41.17
320          37.25
321         135.13
322         477.45
323         440.12
324          67.70
325         168.51
326          31.86
327          40.87
328         109.59
329         206.87
330         134.38
331          56.06
332         264.08
333         240.77
334          91.72
335          49.01
336         107.87
337          62.01
338          36.69
339          35.00
340         256.37
341          47.84
342         125.87
343          42.39
344         117.53
345          43.28
346         144.54
347         126.48
348         125.29
349         229.74
350         124.60
351         143.86
352          56.89
353          46.78
354           3.98
355          72.66
356          50.10
357          85.79
358          63.70
359        1586.47
360         433.07
361         642.02
362         263.95
363         134.99
364          57.89
365         383.99
366         159.31
367         756.91
368         156.22
369         132.95
370          48.27
371         107.35
372         110.20
373         368.92
374         106.85
375         281.50
376          54.25
377         121.78
378         102.26
379          90.62
380          75.69
381          42.86
382          35.70
383         444.25
384          69.16
385          30.00
386          65.71
387          29.29
388          37.74
389          30.00
390         145.90
391          79.88
392         108.00
393         348.74
394          88.78
395         953.71
396         125.77
397          64.05
398         127.69
399          62.42
400          55.69
401         146.13
402         349.99
403          91.28
404         108.64
405         158.98
406          20.75
407          72.90
408         543.83
409          67.12
410         139.07
411         126.68
412          41.42
413         203.16
414         540.02
415         368.60
416         107.78
417         387.27
418         107.23
419         101.25
420          26.09
421         244.35
422         117.85
423         171.32
424         202.44
425          73.03
426         264.67
427          68.70
428          55.13
429          92.99
430          36.00
431          17.87
432          58.38
433          50.00
434        1995.69
435         130.14
436         710.23
437          68.00
438          59.51
439         371.94
440         667.99
441          63.89
442          49.34
443         147.00
444         354.64
445          59.71
446         408.66
447          51.66
448         386.46
449          69.54
450          21.94
451          52.34
452         114.25
453         162.83
454         172.92
455          81.72
456         151.79
457         243.62
458          56.42
459          45.13
460         108.64
461          64.51
462         193.50
463         110.63
464         200.55
465          41.71
466          54.43
467          77.64
468         280.08
469         101.34
470          77.57
471          60.20
472          48.10
473          76.02
474          84.56
475          20.00
476          48.16
477         265.41
478         127.53
479         128.73
480          37.37
481         150.15
482          36.16
483         198.00
484         112.40
485          35.40
486         189.98
487         228.60
488         314.21
489          22.29
490         257.30
491         162.99
492          51.03
493         190.09
494         374.24
495          53.15
496          88.20
497          25.90
498          46.81
499         131.47
500         258.71
501          84.23
502         156.73
503          69.90
504          48.13
505         187.15
506          69.99
507          25.00
508         162.10
509          57.11
510         154.87
511         236.81
512         102.53
513          65.10
514          93.64
515          64.09
516         279.40
517         205.43
518          89.57
519          75.07
520          63.23
521           0.52
522         231.27
523          41.69
524          69.41
525          72.75
526          24.29
527          88.49
528          71.66
529          80.81
530         132.82
531         394.07
532         165.50
533          98.47
534          49.77
535         180.91
536          40.63
537          71.63
538         262.94
539          62.22
540         311.57
541          93.22
542         100.21
543         125.43
544          80.55
545         373.44
546          62.31
547          36.35
548          29.38
549         102.47
550         130.00
551          69.13
552          86.24
553          74.29
554          70.72
555         199.00
556         340.47
557          48.74
558          28.08
559          59.90
560         166.29
561          51.10
562          67.83
563         164.35
564          79.09
565          93.69
566          59.82
567         159.03
568          92.57
569          42.77
570         453.74
571         234.08
572          67.62
573          19.33
574         143.18
575         112.83
576          85.92
577         102.05
578         134.12
579         112.13
580          70.75
581          77.60
582         197.04
583          93.18
584          44.72
585          26.38
586         149.14
587         106.32
588         246.96
589          22.29
590          57.48
591         105.28
592         203.54
593         330.40
594         108.68
595         415.93
596         314.21
597         206.08
598          27.70
599          19.48
600         121.09
601         206.76
602         142.21
603          73.34
604          72.62
605          86.24
606         230.10
607         206.14
608         212.73
609          94.82
610         126.44
611         140.08
612          68.87
613          87.58
614         305.19
615         161.88
616          88.08
617          92.50
618          43.00
619         116.36
620          64.48
621          37.69
622         150.52
623         314.30
624         396.35
625          98.33
626         120.92
627          76.17
628         104.43
629         105.94
630         110.04
631         730.95
632         128.77
633          82.10
634          53.39
635          61.79
636          86.83
637          45.30
638          25.50
639         103.79
640         114.28
641          57.78
642         124.15
643          64.10
644         179.92
645          40.01
646         104.27
647         307.96
648          31.29
649          38.13
650          52.01
651          35.05
652         186.49
653          99.95
654         215.62
655         206.20
656          55.06
657          21.04
658          26.45
659         127.53
660         223.14
661          56.41
662         566.63
663          39.41
664         148.64
665          64.00
666         151.09
667          93.91
668          71.14
669         188.06
670         257.21
671         692.94
672         181.10
673         202.26
674         164.15
675         137.13
676           2.01
677         272.58
678          87.36
679          16.54
680         234.19
681          86.37
682          33.00
683          10.89
684          84.14
685          43.28
686          47.95
687          76.08
688         104.37
689          69.61
690         121.09
691         238.65
692         181.59
693         135.26
694          51.09
695        1783.44
696         145.01
697         231.27
698          70.03
699        1432.92
700          45.24
701          50.00
702          64.01
703         148.18
704         171.53
705          86.15
706          22.79
707          58.16
708         149.42
709          44.53
710         152.82
711          82.92
712          66.69
713          52.75
714         105.94
715         413.31
716         112.09
717         186.36
718         165.22
719          49.02
720         173.68
721         205.07
722          21.04
723         132.68
724          36.09
725          66.44
726         161.62
727          27.75
728          91.28
729          81.93
730         167.92
731          61.36
732          60.00
733          39.01
734          39.78
735          64.23
736         186.92
737          43.29
738          59.13
739          33.51
740          33.10
741         148.06
742         189.56
743         105.38
744          69.06
745          85.24
746         179.46
747         168.35
748         100.00
749          77.89
750          99.43
751         407.90
752          15.00
753         424.04
754         157.20
755         162.03
756         188.50
757          65.47
758          39.42
759         365.32
760          65.11
761         188.34
762          35.40
763         590.72
764          36.75
765          81.73
766          17.86
767         108.97
768         569.66
769          48.13
770          63.10
771          39.42
772          74.03
773          66.78
774          36.59
775         272.64
776          64.34
777          49.05
778         163.69
779         443.85
780         165.31
781        1180.51
782         706.84
783          20.00
784         135.97
785          56.99
786          43.58
787          48.15
788          76.87
789           2.78
790         123.59
791         128.07
792         185.84
793          85.81
794         149.54
795          32.38
796          23.38
797          98.86
798         124.21
799         191.58
800         123.04
801          26.38
802          71.49
803         153.98
804          55.91
805          86.06
806          33.10
807         360.29
808         105.24
809         114.85
810           0.01
811          65.57
812          88.90
813          76.78
814         680.96
815          27.91
816          61.79
817          40.96
818         149.00
819          75.70
820         356.90
821         165.96
822          61.19
823          43.37
824          40.86
825          84.81
826           8.24
827         191.93
828          32.72
829          32.77
830          50.50
831          37.05
832          70.36
833          38.00
834         196.81
835          46.84
836         367.20
837         195.36
838         144.80
839          28.62
840         160.74
841         103.59
842          10.39
843          31.75
844         116.23
845          40.43
846          66.64
847          17.01
848         189.96
849         170.37
850          50.90
851         133.64
852         543.29
853          42.75
854         161.01
855          72.83
856        1605.14
857         130.60
858          69.67
859          70.97
860         255.76
861          75.40
862         109.93
863          71.14
864         113.33
865         292.86
866         129.15
867         177.67
868          27.48
869         140.94
870          23.00
871          49.09
872          84.79
873         111.02
874          42.44
875         210.56
876          42.74
877          50.10
878          67.23
879          46.66
880         201.05
881          81.47
882          79.69
883          45.12
884         250.04
885         108.88
886         189.66
887         135.47
888         104.07
889         184.08
890         164.01
891          91.21
892         129.00
893          84.28
894          57.67
895          97.79
896          53.90
897          35.09
898         218.04
899          67.93
900          40.53
901          97.23
902         159.39
903         167.07
904          50.00
905          93.40
906         276.11
907         149.16
908         175.13
909         143.99
910         131.80
911          88.54
912         109.31
913          63.05
914         353.29
915         276.44
916          45.95
917         116.99
918          46.00
919          23.23
920         119.18
921          32.13
922         222.15
923          59.22
924         204.81
925          73.34
926         131.03
927          57.69
928          27.79
929         224.45
930         135.60
931          76.08
932          67.14
933         137.97
934          68.12
935          73.61
936         117.94
937          84.52
938         138.84
939           5.37
940         119.48
941          77.50
942          84.05
943         149.73
944          93.80
945          76.51
946         121.60
947         528.69
948          73.03
949          70.00
950         278.63
951          89.88
952         117.38
953         180.47
954         110.77
955          28.70
956          23.47
957          50.00
958         364.46
959          48.23
960          78.97
961         159.80
962          66.44
963          71.13
964          76.29
965         188.93
966          70.03
967          51.01
968         162.75
969          36.36
970         209.46
971          79.95
972         134.49
973         111.02
974          53.88
975          62.91
976         335.47
977          12.29
978         237.54
979         131.94
980         191.28
981          85.24
982          37.99
983         200.75
984         213.03
985          74.16
986          55.09
987          10.04
988          57.80
989          25.05
990         199.43
991         172.29
992         126.30
993         116.97
994         158.21
995         247.16
996          45.09
997         172.16
998         189.37
999         372.67
1000         64.44
1001          2.35
1002        204.07
1003         75.17
1004        177.11
1005         42.78
1006         37.79
1007        119.79
1008        273.98
1009         63.70
1010         50.00
1011         36.05
1012         85.15
1013         50.45
1014         34.37
1015        184.93
1016        157.97
1017        143.15
1018        123.25
1019        121.68
1020        156.39
1021        171.79
1022        133.05
1023         77.42
1024        281.73
1025         36.07
1026        441.16
1027         99.14
1028        118.35
1029         92.80
1030        142.25
1031        186.27
1032         23.88
1033        497.59
1034         51.57
1035        159.07
1036        154.38
1037        245.36
1038        385.52
1039        318.17
1040        576.20
1041         93.66
1042         71.81
1043         33.10
1044          3.90
1045         44.24
1046        398.88
1047         47.61
1048        116.85
1049         35.09
1050         51.88
1051        190.83

In [19]:
merged_df = pd.merge(
    orders,
    customers,
    on="customer_id",
    how="left"
)
merged_df.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,approval_hours,estimated_vs_actual_days,purchased_month,purchased_year,purchased_weekday,purchased_hour,day_type,customer_unique_id,customer_zip_code_prefix,Customer_City,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8,0.183333,7,October,2017,Monday,10,Weekday,7c396fd4830fd04220f754e42b4e5bff,3149,Sao Paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,Delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,13,30.716667,5,July,2018,Tuesday,20,Weekday,af07308b275d755c9edb36a90c618231,47813,Barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,Delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,9,0.283333,17,August,2018,Wednesday,8,Weekday,3a653a41f6f9fc3d2a113cf8398680e8,75265,Vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,Delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,13,0.283333,12,November,2017,Saturday,19,Weekend,7c142cf63193a1473d2e66489a9ae977,59296,Sao Goncalo Do Amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,Delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2,1.033333,9,February,2018,Tuesday,21,Weekday,72632f0f9dd73dfee390c9b22eb56dd6,9195,Santo Andre,SP
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,Delivered,2017-07-09 21:57:00,2017-07-09 22:10:00,2017-07-11 14:58:00,2017-07-26 10:57:00,2017-08-01,16,0.216667,5,July,2017,Sunday,21,Weekend,80bb27c7c16e8f973207a5086ab329e2,86320,Congonhinhas,PR
6,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,Delivered,2017-05-16 13:10:00,2017-05-16 13:22:00,2017-05-22 10:07:00,2017-05-26 12:55:00,2017-06-07,9,0.200000,11,May,2017,Tuesday,13,Weekday,932afa1e708222e5821dac9cd5db4cae,26525,Nilopolis,RJ
7,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,Delivered,2017-01-23 18:29:00,2017-01-25 02:50:00,2017-01-26 14:16:00,2017-02-02 14:08:00,2017-03-06,9,32.350000,31,January,2017,Monday,18,Weekday,39382392765b6dc74812866ee5ee92a7,99655,Faxinalzinho,RS
8,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,Delivered,2017-07-29 11:55:00,2017-07-29 12:05:00,2017-08-10 19:45:00,2017-08-16 17:14:00,2017-08-23,18,0.166667,6,July,2017,Saturday,11,Weekend,299905e3934e9e181bfb2e164dd4b4f8,18075,Sorocaba,SP
9,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,Delivered,2017-05-16 19:41:00,2017-05-16 19:50:00,2017-05-18 11:40:00,2017-05-29 11:18:00,2017-06-07,12,0.150000,8,May,2017,Tuesday,19,Weekday,f2a85dec752b8517b5e58a06ff3cd937,20780,Rio De Janeiro,RJ

In [20]:
merged_df.shape

(96475, 20)

In [21]:
orders.shape

(96475, 16)

In [24]:
merged_df.isnull().sum()
merged_df[merged_df["order_approved_at"].isna()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,approval_hours,estimated_vs_actual_days,purchased_month,purchased_year,purchased_weekday,purchased_hour,day_type,customer_unique_id,customer_zip_code_prefix,Customer_City,customer_state
5171,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,Delivered,2017-02-18 14:40:00,NaN,2017-02-23 12:04:00,2017-03-01 13:25:00,2017-03-17,10,NaN,15,February,2017,Saturday,14,Weekend,8a9a08c7ca8900a200d83cf838a07e0b,6708,Cotia,SP
16099,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,Status Pending,2017-02-18 12:45:00,NaN,2017-02-23 09:01:00,2017-03-02 10:05:00,2017-03-21,11,NaN,18,February,2017,Saturday,12,Weekend,91efb7fcabc17925099dced52435837f,93548,Novo Hamburgo,RS
18495,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,Status Pending,2017-02-18 13:29:00,NaN,2017-02-22 16:25:00,2017-03-01 08:07:00,2017-03-17,10,NaN,15,February,2017,Saturday,13,Weekend,e1f01a1bd6485e58ad3c769a5427d8a8,8230,Sao Paulo,SP
21999,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,Status Pending,2017-02-18 16:48:00,NaN,2017-02-22 11:23:00,2017-03-09 07:28:00,2017-03-31,18,NaN,21,February,2017,Saturday,16,Weekend,7e1a5ca61b572d76b64b6688b9f96473,62700,Caninde,CE
22478,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,Status Pending,2017-02-17 13:05:00,NaN,2017-02-22 11:23:00,2017-03-02 11:09:00,2017-03-20,12,NaN,17,February,2017,Friday,13,Weekday,c8822fce1d0bfa7ddf0da24fff947172,27945,Macae,RJ
26014,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,Status Pending,2017-01-19 12:48:00,NaN,2017-01-25 14:56:00,2017-01-30 18:16:00,2017-03-01,11,NaN,29,January,2017,Thursday,12,Weekday,6ff8b0d7b35d5c945633b8d60165691b,11030,Santos,SP
37158,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,Status Pending,2017-02-19 01:28:00,NaN,2017-02-23 03:11:00,2017-03-02 03:41:00,2017-03-27,11,NaN,24,February,2017,Sunday,1,Weekend,2e0a2166aa23da2472c6a60c4af6f7a6,3573,Sao Paulo,SP
38171,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,Status Pending,2017-02-18 11:04:00,NaN,2017-02-23 07:23:00,2017-03-02 16:15:00,2017-03-22,12,NaN,19,February,2017,Saturday,11,Weekend,c4c0011e639bdbcf26059ddc38bd3c18,13225,Varzea Paulista,SP
46956,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,Status Pending,2017-01-19 22:26:00,NaN,2017-01-27 11:08:00,2017-02-06 14:22:00,2017-03-16,17,NaN,37,January,2017,Thursday,22,Weekday,d49f3dae6bad25d05160fc17aca5942d,36400,Conselheiro Lafaiete,MG
59913,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,Status Pending,2017-02-17 17:21:00,NaN,2017-02-22 11:42:00,2017-03-03 12:16:00,2017-03-20,13,NaN,16,February,2017,Friday,17,Weekday,5a4fa4919cbf2b049e72be460a380e5b,35620,Abaete,MG
61163,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,Status Pending,2017-02-18 15:52:00,NaN,2017-02-23 03:09:00,2017-03-07 13:57:00,2017-03-29,16,NaN,21,February,2017,Saturday,15,Weekend,79af1bbf230a2630487975aa5d7d6220,37660,Paraisopolis,MG
65679,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,Status Pending,2017-02-18 22:49:00,NaN,2017-02-22 11:31:00,2017-03-02 12:06:00,2017-03-21,11,NaN,18,February,2017,Saturday,22,Weekend,bc1896dc77f49e6dec880445a9b443a3,21020,Rio De Janeiro,RJ
70260,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,Status Pending,2017-02-17 15:53:00,NaN,2017-02-22 11:31:00,2017-03-03 11:47:00,2017-03-23,13,NaN,19,February,2017,Friday,15,Weekday,c094ac95fcd52f821809ec232a7a6956,95795,Sao Vendelino,RS
82451,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,Status Pending,2017-02-18 17:15:00,NaN,2017-02-22 11:23:00,2017-03-03 18:43:00,2017-03-31,13,NaN,27,February,2017,Saturday,17,Weekend,f79be7c08dd24b72d34634f1b89333a4,65110,Sao Jose De Ribamar,MA

In [25]:
merged_df.isnull().sum()

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      0
order_delivered_customer_date     0
order_estimated_delivery_date     0
delivery_days                     0
approval_hours                   14
estimated_vs_actual_days          0
purchased_month                   0
purchased_year                    0
purchased_weekday                 0
purchased_hour                    0
day_type                          0
customer_unique_id                0
customer_zip_code_prefix          0
Customer_City                     0
customer_state                    0
dtype: int64

In [26]:
orders[["order_approved_at", "approval_hours"]].isna().sum()

order_approved_at    14
approval_hours       14
dtype: int64

In [43]:
merged_df = pd.merge(
    merged_df,
    payments,
    on="order_id",
    how="left"
)

In [44]:
merged_df.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,approval_hours,...,purchased_hour,day_type,customer_unique_id,customer_zip_code_prefix,Customer_City,customer_state,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8,0.183333,...,10,Weekday,7c396fd4830fd04220f754e42b4e5bff,3149,Sao Paulo,SP,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8,0.183333,...,10,Weekday,7c396fd4830fd04220f754e42b4e5bff,3149,Sao Paulo,SP,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8,0.183333,...,10,Weekday,7c396fd4830fd04220f754e42b4e5bff,3149,Sao Paulo,SP,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,Delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,13,30.716667,...,20,Weekday,af07308b275d755c9edb36a90c618231,47813,Barreiras,BA,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,Delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,9,0.283333,...,8,Weekday,3a653a41f6f9fc3d2a113cf8398680e8,75265,Vianopolis,GO,1.0,credit_card,3.0,179.12
5,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,Delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,13,0.283333,...,19,Weekend,7c142cf63193a1473d2e66489a9ae977,59296,Sao Goncalo Do Amarante,RN,1.0,credit_card,1.0,72.20
6,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,Delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2,1.033333,...,21,Weekday,72632f0f9dd73dfee390c9b22eb56dd6,9195,Santo Andre,SP,1.0,credit_card,1.0,28.62
7,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,Delivered,2017-07-09 21:57:00,2017-07-09 22:10:00,2017-07-11 14:58:00,2017-07-26 10:57:00,2017-08-01,16,0.216667,...,21,Weekend,80bb27c7c16e8f973207a5086ab329e2,86320,Congonhinhas,PR,1.0,credit_card,6.0,175.26
8,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,Delivered,2017-05-16 13:10:00,2017-05-16 13:22:00,2017-05-22 10:07:00,2017-05-26 12:55:00,2017-06-07,9,0.200000,...,13,Weekday,932afa1e708222e5821dac9cd5db4cae,26525,Nilopolis,RJ,1.0,credit_card,3.0,75.16
9,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,Delivered,2017-01-23 18:29:00,2017-01-25 02:50:00,2017-01-26 14:16:00,2017-02-02 14:08:00,2017-03-06,9,32.350000,...,18,Weekday,39382392765b6dc74812866ee5ee92a7,99655,Faxinalzinho,RS,1.0,boleto,1.0,35.95

In [45]:
merged_df2.shape
merged_df2.isnull().sum()
merged_df.shape

(100754, 24)

In [46]:
merged_df["payment_sequential"].value_counts().head()

payment_sequential
1.0    96396
2.0     2951
3.0      564
4.0      267
5.0      163
Name: count, dtype: int64

In [47]:
merged_df = pd.merge(
    merged_df,
    reviews,
    on="order_id",
    how="left"
)

In [48]:
merged_df.shape

(101323, 30)

In [49]:
merged_df = pd.merge(
    merged_df,
    order_items,
    on="order_id",
    how="left"
)

In [51]:
merged_df.shape

(115676, 37)

In [52]:
merged_df=pd.merge(
    merged_df,
    products,
    on="product_id",
    how="left"
)

In [56]:
merged_df.shape

(115676, 48)

In [54]:
merged_df = pd.merge(
    merged_df,
    sellers,
    on="seller_id",
    how="left"
)

In [57]:
merged_df.shape

(115676, 48)

In [58]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115676 entries, 0 to 115675
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115676 non-null  object
 1   customer_id                    115676 non-null  object
 2   order_status                   115676 non-null  object
 3   order_purchase_timestamp       115676 non-null  object
 4   order_approved_at              115661 non-null  object
 5   order_delivered_carrier_date   115676 non-null  object
 6   order_delivered_customer_date  115676 non-null  object
 7   order_estimated_delivery_date  115676 non-null  object
 8   delivery_days                  115676 non-null  int64
 9   approval_hours                 115661 non-null  float64
 10  estimated_vs_actual_days       115676 non-null  int64
 11  purchased_month                115676 non-null  object
 12  purchased_year                 115676 non-null  int64
 13  purchased_weekday              115676 non-null  object
 14  purchased_hour                 115676 non-null  int64
 15  day_type                       115676 non-null  object
 16  customer_unique_id             115676 non-null  object
 17  customer_zip_code_prefix       115676 non-null  int64
 18  Customer_City                  115676 non-null  object
 19  customer_state                 115676 non-null  object
 20  payment_sequential             115673 non-null  float64
 21  payment_type                   115673 non-null  object
 22  payment_installments           115673 non-null  float64
 23  payment_value                  115673 non-null  object
 24  review_id                      114815 non-null  object
 25  review_score                   114815 non-null  float64
 26  review_comment_title           114815 non-null  object
 27  review_comment_message         114815 non-null  object
 28  review_creation_date           114815 non-null  object
 29  review_answer_timestamp        114815 non-null  object
 30  order_item_id                  115333 non-null  float64
 31  product_id                     115333 non-null  object
 32  seller_id                      115333 non-null  object
 33  shipping_limit_date            115333 non-null  object
 34  price                          115333 non-null  float64
 35  freight_value                  115333 non-null  float64
 36  price_range                    115333 non-null  object
 37  Product_Category_Name          113696 non-null  object
 38  product_name_length            113696 non-null  float64
 39  product_description_length     113696 non-null  float64
 40  product_photos_qty             113696 non-null  float64
 41  product_weight_g               113696 non-null  float64
 42  product_length_cm              113696 non-null  float64
 43  product_height_cm              113696 non-null  float64
 44  product_width_cm               113696 non-null  float64
 45  seller_zip_code_prefix         115333 non-null  float64
 46  Seller_City                    115333 non-null  object
 47  Seller_State                   115333 non-null  object
dtypes: float64(15), int64(5), object(28)
memory usage: 42.4+ MB

In [65]:
merged_df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_days', 'approval_hours', 'estimated_vs_actual_days',
       'purchased_month', 'purchased_year', 'purchased_weekday',
       'purchased_hour', 'day_type', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'price_range',
       'Product_Category_Name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state'],
      dtype='object')

In [64]:
merged_df.rename(
    columns={"Seller_City": "seller_city", "Seller_State": "seller_state","Customer_City":"customer_city"},
    inplace=True
)

In [68]:
merged_df.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
delivery_days                       0
approval_hours                     15
estimated_vs_actual_days            0
purchased_month                     0
purchased_year                      0
purchased_weekday                   0
purchased_hour                      0
day_type                            0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
review_id                         861
review_score                      861
review_comment_title              861
review_comment_message            861
review_creation_date              861
review_answer_timestamp           861
order_item_id                     343
product_id                        343
seller_id                         343
shipping_limit_date               343
price                             343
freight_value                     343
price_range                       343
Product_Category_Name            1980
product_name_length              1980
product_description_length       1980
product_photos_qty               1980
product_weight_g                 1980
product_length_cm                1980
product_height_cm                1980
product_width_cm                 1980
seller_zip_code_prefix            343
seller_city                       343
seller_state                      343
dtype: int64

In [69]:
merged_df.isna().sum().sort_values(ascending=False)

Product_Category_Name            1980
product_width_cm                 1980
product_height_cm                1980
product_length_cm                1980
product_weight_g                 1980
product_photos_qty               1980
product_description_length       1980
product_name_length              1980
review_answer_timestamp           861
review_comment_message            861
review_creation_date              861
review_id                         861
review_score                      861
review_comment_title              861
price_range                       343
freight_value                     343
price                             343
shipping_limit_date               343
seller_id                         343
product_id                        343
order_item_id                     343
seller_zip_code_prefix            343
seller_city                       343
seller_state                      343
order_approved_at                  15
approval_hours                     15
payment_installments                3
payment_type                        3
payment_sequential                  3
payment_value                       3
customer_id                         0
estimated_vs_actual_days            0
order_status                        0
order_purchase_timestamp            0
order_delivered_carrier_date        0
order_delivered_customer_date       0
order_estimated_delivery_date       0
delivery_days                       0
purchased_year                      0
purchased_month                     0
purchased_weekday                   0
purchased_hour                      0
day_type                            0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_id                            0
dtype: int64

In [70]:
merged_df[merged_df["product_id"].isna()][
    ["order_id", "order_status"]
].head(10)

                              order_id order_status
232   6d7de866a140b19d09e825b2a4e944c7    Delivered
480   d62387acb3914789e712406e9882e549    Delivered
746   f29d0fd6d4e6d5ce550e0b2f9335116c    Delivered
769   a2ea081c06c12c25c068089e4985745a    Delivered
1011  f7fd9088963ee4f442fd642219d80fb5    Delivered
1289  d0bec96aad189992b278688279ba1511    Delivered
1380  67d8f4eb477222d7b5b81daa8e007bdd    Delivered
1991  654c6463f421d51939eae082dcc3b15e    Delivered
2626  9bd90698ab1e822ca4cb1e2a0de42fd4    Delivered
2771  24c0b5c7e8f51f85f1bcdbe4cd0f81ac    Delivered

In [71]:
merged_df.shape

(115676, 48)

In [72]:
order_items["order_id"].isna().sum()

0

In [73]:
orders["order_id"].isin(order_items["order_id"]).value_counts()

order_id
True     96139
False      336
Name: count, dtype: int64

In [74]:
orders["order_id"].nunique()

96475

In [75]:
order_items["order_id"].nunique()

98328

In [76]:
orders.loc[
    ~orders["order_id"].isin(order_items["order_id"])
].shape

(336, 16)

In [ ]:
order_items.loc[
    ~order_items["order_id"].isin(orders["order_id"])
].shape

(2453, 8)

In [78]:
missing_orders = order_items.loc[
    ~order_items["order_id"].isin(orders["order_id"])
]

missing_orders["order_id"].nunique()

2189

In [80]:
merged_df.to_csv("olist_master_dataset.csv", index=False)

In [81]:
df = pd.read_csv("olist_master_dataset.csv")
df.head(10)

C:\Users\Mohammed mustafa\AppData\Local\Temp\ipykernel_13152\4003913186.py:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("olist_master_dataset.csv")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,approval_hours,...,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8,0.183333,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,Maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8,0.183333,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,Maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,Delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,8,0.183333,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,Maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,Delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,13,30.716667,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,Belo Horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,Delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,9,0.283333,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,Guariba,SP
5,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,Delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,13,0.283333,...,59.0,468.0,3.0,450.0,30.0,10.0,20.0,31842.0,Belo Horizonte,MG
6,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,Delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2,1.033333,...,38.0,316.0,4.0,250.0,51.0,15.0,15.0,8752.0,Mogi Das Cruzes,SP
7,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,Delivered,2017-07-09 21:57:00,2017-07-09 22:10:00,2017-07-11 14:58:00,2017-07-26 10:57:00,2017-08-01,16,0.216667,...,49.0,608.0,1.0,7150.0,65.0,10.0,65.0,7112.0,Guarulhos,SP
8,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,Delivered,2017-05-16 13:10:00,2017-05-16 13:22:00,2017-05-22 10:07:00,2017-05-26 12:55:00,2017-06-07,9,0.200000,...,59.0,956.0,1.0,50.0,16.0,16.0,17.0,12940.0,Atibaia,SP
9,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,Delivered,2017-01-23 18:29:00,2017-01-25 02:50:00,2017-01-26 14:16:00,2017-02-02 14:08:00,2017-03-06,9,32.350000,...,41.0,432.0,2.0,300.0,35.0,35.0,15.0,13720.0,Sao Jose Do Rio Pardo,SP